spring.application.name=DirtyPenguin-Core


# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/dirtypenguin
spring.datasource.username=ethan
spring.datasource.password=9908


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Server
server.port=8080